'use client';

import { useState, useEffect } from 'react';
import { Card } from '@/components/ui/card';
import { Button } from '@/components/ui/button';
import { BackButton } from '@/components/ui/back-button';
import { Breadcrumb } from '@/components/ui/breadcrumb';
import { LoadingSkeleton } from '@/components/ui/loading-skeleton';
import { GlassCard } from '@/components/ui/glass-card';
import { FadeIn } from '@/components/ui/animate';
import { Select, SelectTrigger, SelectValue, SelectContent, SelectItem } from '@/components/ui/select';
import { DollarSign, TrendingUp, TrendingDown, ShoppingCart, Package, AlertTriangle, Save, History } from 'lucide-react';
import { toast } from 'sonner';

interface CMVData {
  period: number;
  cmv: number;
  cmvPercent: number;
  cmvChange: number;
  purchases: number;
  consumption: number;
  losses: number;
  estimatedRevenue: number;
  topIngredients: Array<{ id: string; name: string; purchases: number; consumption: number; losses: number; total: number }>;
  dailyChart: Array<{ date: string; purchases: number; consumption: number }>;
  idealRange: { min: number; max: number };
}

interface Snapshot {
  id: string;
  periodStart: string;
  periodEnd: string;
  periodDays: number;
  totalCMV: number;
  cmvPercent: number;
  revenue: number;
  alertLevel: 'NORMAL' | 'WARNING' | 'CRITICAL';
  alertMessage?: string | null;
  autoGenerated: boolean;
  createdAt: string;
}

export default function CMVPage() {
  const [data, setData] = useState<CMVData | null>(null);
  const [history, setHistory] = useState<Snapshot[]>([]);
  const [latestSnapshot, setLatestSnapshot] = useState<Snapshot | null>(null);
  const [loading, setLoading] = useState(true);
  const [saving, setSaving] = useState(false);
  const [period, setPeriod] = useState('30');

  useEffect(() => {
    fetchAll();
  }, [period]);

  const fetchAll = async () => {
    try {
      setLoading(true);
      const [cmvRes, histRes] = await Promise.all([
        fetch(`/api/cmv?period=${period}`),
        fetch('/api/cmv/history?limit=30'),
      ]);
      if (!cmvRes.ok) throw new Error();
      setData(await cmvRes.json());
      if (histRes.ok) {
        const h = await histRes.json();
        setHistory(h.snapshots || []);
        setLatestSnapshot(h.latest || null);
      }
    } catch {
      toast.error('Erro ao carregar dados de CMV');
    } finally {
      setLoading(false);
    }
  };

  const createSnapshot = async () => {
    try {
      setSaving(true);
      const res = await fetch('/api/cmv/snapshot', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ period: parseInt(period) }),
      });
      if (!res.ok) throw new Error();
      toast.success('Snapshot salvo no histórico!');
      fetchAll();
    } catch {
      toast.error('Erro ao salvar snapshot');
    } finally {
      setSaving(false);
    }
  };

  const fmt = (v: number) => `R$ ${v.toFixed(2).replace('.', ',').replace(/\B(?=(\d{3})+(?!\d))/g, '.')}`;
  const fmtShort = (v: number) => {
    if (v >= 1000) return `R$ ${(v / 1000).toFixed(1)}k`;
    return `R$ ${v.toFixed(0)}`;
  };
  const fmtDate = (s: string) => {
    const d = new Date(s);
    return `${d.getDate().toString().padStart(2, '0')}/${(d.getMonth() + 1).toString().padStart(2, '0')}`;
  };

  const getCMVStatus = (percent: number) => {
    if (percent === 0) return { label: 'Sem dados', color: 'text-slate-500', bg: 'bg-slate-50' };
    if (percent <= 28) return { label: 'Excelente', color: 'text-emerald-600', bg: 'bg-emerald-50' };
    if (percent <= 35) return { label: 'Ideal', color: 'text-blue-600', bg: 'bg-blue-50' };
    if (percent <= 40) return { label: 'Atenção', color: 'text-amber-600', bg: 'bg-amber-50' };
    return { label: 'Crítico', color: 'text-red-600', bg: 'bg-red-50' };
  };

  const maxHistCmvPct = Math.max(...history.map(h => h.cmvPercent), 45);

  return (
    <div className="space-y-4 p-4 sm:space-y-6 sm:p-6">
      <Breadcrumb items={[{ label: 'Dashboard', href: '/dashboard' }, { label: 'CMV' }]} />
      <div className="flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between">
        <div className="flex items-center gap-4">
          <BackButton href="/dashboard" label="Voltar" />
          <div>
            <h1 className="text-xl sm:text-3xl font-bold">Calculadora de CMV</h1>
            <p className="text-sm text-muted-foreground">Custo de Mercadoria Vendida · Snapshots + Alertas automáticos</p>
          </div>
        </div>
        <div className="flex gap-2">
          <Button onClick={createSnapshot} disabled={saving || !data} size="sm" variant="outline">
            <Save className="h-4 w-4 mr-1" />
            {saving ? 'Salvando...' : 'Salvar snapshot'}
          </Button>
          <Select value={period} onValueChange={setPeriod}>
            <SelectTrigger className="w-full sm:w-[180px]">
              <SelectValue />
            </SelectTrigger>
            <SelectContent>
              <SelectItem value="7">Últimos 7 dias</SelectItem>
              <SelectItem value="15">Últimos 15 dias</SelectItem>
              <SelectItem value="30">Últimos 30 dias</SelectItem>
              <SelectItem value="60">Últimos 60 dias</SelectItem>
              <SelectItem value="90">Últimos 90 dias</SelectItem>
            </SelectContent>
          </Select>
        </div>
      </div>

      {/* Alert banner do snapshot mais recente */}
      {latestSnapshot && latestSnapshot.alertLevel !== 'NORMAL' && latestSnapshot.alertMessage && (
        <Card className={`p-4 border-l-4 ${
          latestSnapshot.alertLevel === 'CRITICAL'
            ? 'border-l-red-500 bg-red-50 dark:bg-red-900/20'
            : 'border-l-amber-500 bg-amber-50 dark:bg-amber-900/20'
        }`}>
          <div className="flex items-start gap-3">
            <AlertTriangle className={`h-5 w-5 shrink-0 mt-0.5 ${
              latestSnapshot.alertLevel === 'CRITICAL' ? 'text-red-600' : 'text-amber-600'
            }`} />
            <div className="flex-1">
              <p className="font-semibold text-sm">
                {latestSnapshot.alertLevel === 'CRITICAL' ? 'Alerta crítico de CMV' : 'Atenção no CMV'}
              </p>
              <p className="text-sm mt-0.5">{latestSnapshot.alertMessage}</p>
              <p className="text-xs text-muted-foreground mt-1">
                Último snapshot em {new Date(latestSnapshot.createdAt).toLocaleString('pt-BR')}
              </p>
            </div>
          </div>
        </Card>
      )}

      {loading ? (
        <div className="space-y-4">
          <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-4">
            {Array.from({ length: 4 }).map((_, i) => <LoadingSkeleton key={i} variant="card" height="h-28" />)}
          </div>
          <LoadingSkeleton variant="card" height="h-64" />
        </div>
      ) : data ? (
        <FadeIn>
          <div className="space-y-6">
            {/* CMV Principal */}
            <GlassCard className="p-6">
              <div className="flex flex-col sm:flex-row sm:items-center sm:justify-between gap-4">
                <div>
                  <p className="text-sm text-muted-foreground font-medium">CMV do Período</p>
                  <p className="text-3xl sm:text-4xl font-bold mt-1">{fmt(data.cmv)}</p>
                  {data.cmvChange !== 0 && (
                    <div className={`flex items-center gap-1 mt-2 text-sm ${data.cmvChange > 0 ? 'text-red-600' : 'text-emerald-600'}`}>
                      {data.cmvChange > 0 ? <TrendingUp className="h-4 w-4" /> : <TrendingDown className="h-4 w-4" />}
                      <span>{Math.abs(data.cmvChange).toFixed(1)}% vs período anterior</span>
                    </div>
                  )}
                </div>
                <div className="text-center">
                  {(() => {
                    const status = getCMVStatus(data.cmvPercent);
                    return (
                      <div className={`px-6 py-4 rounded-xl ${status.bg}`}>
                        <p className="text-sm text-muted-foreground">CMV %</p>
                        <p className={`text-3xl font-bold ${status.color}`}>
                          {data.cmvPercent > 0 ? `${data.cmvPercent.toFixed(1)}%` : 'N/A'}
                        </p>
                        <p className={`text-xs font-medium mt-1 ${status.color}`}>{status.label}</p>
                        <p className="text-xs text-muted-foreground mt-1">Ideal: {data.idealRange.min}-{data.idealRange.max}%</p>
                      </div>
                    );
                  })()}
                </div>
              </div>
            </GlassCard>

            {/* KPI Cards */}
            <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-4">
              <Card className="p-4">
                <div className="flex items-center gap-3">
                  <div className="p-2 rounded-lg bg-blue-50 dark:bg-blue-900/20">
                    <ShoppingCart className="h-5 w-5 text-blue-600" />
                  </div>
                  <div>
                    <p className="text-xs text-muted-foreground">Compras</p>
                    <p className="text-lg font-bold">{fmt(data.purchases)}</p>
                  </div>
                </div>
              </Card>
              <Card className="p-4">
                <div className="flex items-center gap-3">
                  <div className="p-2 rounded-lg bg-orange-50 dark:bg-orange-900/20">
                    <Package className="h-5 w-5 text-orange-600" />
                  </div>
                  <div>
                    <p className="text-xs text-muted-foreground">Consumo</p>
                    <p className="text-lg font-bold">{fmt(data.consumption)}</p>
                  </div>
                </div>
              </Card>
              <Card className="p-4">
                <div className="flex items-center gap-3">
                  <div className="p-2 rounded-lg bg-red-50 dark:bg-red-900/20">
                    <AlertTriangle className="h-5 w-5 text-red-600" />
                  </div>
                  <div>
                    <p className="text-xs text-muted-foreground">Perdas</p>
                    <p className="text-lg font-bold">{fmt(data.losses)}</p>
                  </div>
                </div>
              </Card>
              <Card className="p-4">
                <div className="flex items-center gap-3">
                  <div className="p-2 rounded-lg bg-emerald-50 dark:bg-emerald-900/20">
                    <DollarSign className="h-5 w-5 text-emerald-600" />
                  </div>
                  <div>
                    <p className="text-xs text-muted-foreground">Receita Estimada</p>
                    <p className="text-lg font-bold">{fmt(data.estimatedRevenue)}</p>
                  </div>
                </div>
              </Card>
            </div>

            {/* Histórico de Snapshots */}
            {history.length > 0 && (
              <Card className="p-6">
                <div className="flex items-center gap-2 mb-4">
                  <History className="h-5 w-5 text-muted-foreground" />
                  <h2 className="text-lg font-bold">Histórico de CMV%</h2>
                  <span className="text-xs text-muted-foreground ml-auto">{history.length} snapshot{history.length > 1 ? 's' : ''}</span>
                </div>
                {/* Chart de barras horizontais */}
                <div className="space-y-2">
                  <div className="flex items-end gap-1 h-32 border-b border-slate-200 dark:border-slate-700 pb-1">
                    {history.map((h, idx) => {
                      const heightPct = (h.cmvPercent / maxHistCmvPct) * 100;
                      const color =
                        h.alertLevel === 'CRITICAL' ? 'bg-red-500'
                        : h.alertLevel === 'WARNING' ? 'bg-amber-500'
                        : h.cmvPercent <= 28 ? 'bg-emerald-500' : 'bg-blue-500';
                      return (
                        <div
                          key={h.id}
                          className="flex-1 flex flex-col items-center justify-end group relative"
                          title={`${fmtDate(h.periodEnd)}: ${h.cmvPercent.toFixed(1)}%`}
                        >
                          <div
                            className={`w-full ${color} rounded-t transition-all hover:opacity-80`}
                            style={{ height: `${Math.max(heightPct, 2)}%` }}
                          />
                          <div className="absolute bottom-full mb-1 px-2 py-1 bg-slate-900 text-white text-xs rounded opacity-0 group-hover:opacity-100 pointer-events-none whitespace-nowrap">
                            {fmtDate(h.periodEnd)}: {h.cmvPercent.toFixed(1)}%
                          </div>
                        </div>
                      );
                    })}
                  </div>
                  <div className="flex justify-between text-xs text-muted-foreground">
                    <span>{fmtDate(history[0]?.periodEnd || '')}</span>
                    {history.length > 2 && <span>{fmtDate(history[Math.floor(history.length / 2)]?.periodEnd || '')}</span>}
                    <span>{fmtDate(history[history.length - 1]?.periodEnd || '')}</span>
                  </div>
                  {/* Linha horizontal do ideal */}
                  <div className="flex items-center gap-4 text-xs text-muted-foreground mt-3 flex-wrap">
                    <div className="flex items-center gap-1"><div className="w-3 h-3 bg-emerald-500 rounded-sm" /> Excelente (&lt;28%)</div>
                    <div className="flex items-center gap-1"><div className="w-3 h-3 bg-blue-500 rounded-sm" /> Ideal (28-35%)</div>
                    <div className="flex items-center gap-1"><div className="w-3 h-3 bg-amber-500 rounded-sm" /> Atenção (35-40%)</div>
                    <div className="flex items-center gap-1"><div className="w-3 h-3 bg-red-500 rounded-sm" /> Crítico (&gt;40%)</div>
                  </div>
                </div>
              </Card>
            )}

            {/* Top Ingredients */}
            {data.topIngredients.length > 0 && (
              <Card className="p-6">
                <h2 className="text-lg font-bold mb-4">Top Insumos por Custo</h2>
                <div className="space-y-3">
                  {data.topIngredients.map((ing, i) => {
                    const maxCost = data.topIngredients[0]?.total || 1;
                    const pct = (ing.total / maxCost) * 100;
                    return (
                      <div key={ing.id} className="flex items-center gap-3">
                        <span className="w-6 text-sm font-medium text-muted-foreground">{i + 1}</span>
                        <div className="flex-1">
                          <div className="flex justify-between mb-1">
                            <span className="text-sm font-medium truncate">{ing.name}</span>
                            <span className="text-sm font-bold">{fmt(ing.total)}</span>
                          </div>
                          <div className="h-2 bg-slate-100 dark:bg-slate-800 rounded-full overflow-hidden">
                            <div className="h-full bg-primary rounded-full transition-all" style={{ width: `${pct}%` }} />
                          </div>
                        </div>
                      </div>
                    );
                  })}
                </div>
              </Card>
            )}

            {/* Dica do CMV */}
            <Card className="p-6 border-l-4 border-l-blue-500 bg-blue-50 dark:bg-blue-900/20">
              <h3 className="font-semibold mb-2">💡 Como interpretar o CMV</h3>
              <ul className="space-y-1 text-sm text-muted-foreground">
                <li>• <strong>Abaixo de 28%</strong>: Excelente! Margem muito saudável.</li>
                <li>• <strong>28-35%</strong>: Ideal para a maioria dos restaurantes.</li>
                <li>• <strong>35-40%</strong>: Atenção. Revise preços e perdas.</li>
                <li>• <strong>Acima de 40%</strong>: Crítico. Ação imediata necessária.</li>
              </ul>
              <p className="text-sm text-muted-foreground mt-3">
                Dica: Use o botão <strong>Salvar snapshot</strong> periodicamente para construir o histórico e receber alertas automáticos.
              </p>
            </Card>
          </div>
        </FadeIn>
      ) : null}
    </div>
  );
}
