// @ts-nocheck
import { NextRequest, NextResponse } from 'next/server';
import { getServerSession } from 'next-auth';
import { authOptions } from '@/lib/auth';
import { prisma } from '@/lib/prisma';
import { getCurrentRestaurantId } from '@/lib/whatsapp/get-restaurant';

export const dynamic = 'force-dynamic';

/**
 * POST /api/cmv/snapshot
 * Cria um snapshot do CMV atual e grava no histórico.
 * Pode ser chamado manualmente ou via scheduled task.
 */
export async function POST(req: NextRequest) {
  try {
    // Permitir via sessão OU via CRON_SECRET header
    const isInternal = req.headers.get('x-internal-trigger') === process.env.CRON_SECRET;
    let restaurantId: string | null = null;
    if (!isInternal) {
      const session = await getServerSession(authOptions);
      if (!session) return NextResponse.json({ error: 'Não autorizado' }, { status: 401 });
      restaurantId = await getCurrentRestaurantId();
    }

    const body = await req.json().catch(() => ({}));
    const period = parseInt(body.period || '30');

    const endDate = new Date();
    const startDate = new Date();
    startDate.setDate(startDate.getDate() - period);

    // Internal/cron calls have no session, so they must name the restaurant
    // explicitly; session-authenticated calls always use the caller's own
    // restaurant (never trust a client-supplied restaurantId over the session).
    if (isInternal) {
      restaurantId = body.restaurantId || null;
    }
    if (!restaurantId) {
      return NextResponse.json({ error: 'Nenhum restaurante encontrado' }, { status: 404 });
    }

    // Collect stock movements
    const movements = await prisma.stockMovement.findMany({
      where: {
        createdAt: { gte: startDate, lte: endDate },
        ingredient: { restaurantId },
      },
      include: { ingredient: { select: { referenceCost: true } } },
    });

    let purchases = 0;
    let consumption = 0;
    let losses = 0;
    for (const m of movements) {
      const cost = m.quantity * (m.ingredient?.referenceCost || 0);
      if (m.movementType === 'ENTRY') purchases += cost;
      else if (m.movementType === 'LOSS') losses += cost;
      else if (m.movementType !== 'ADJUSTMENT') consumption += cost;
    }
    const totalCMV = consumption + losses;

    // Revenue from order session items (actual sales) with fallback to production plans
    const sessionItems = await prisma.orderSessionItem.findMany({
      where: {
        addedAt: { gte: startDate, lte: endDate },
        session: { status: { not: 'CANCELLED' as any }, restaurantId },
      },
      select: { quantity: true, price: true },
    });
    let revenue = sessionItems.reduce((s, i) => s + i.quantity * Number(i.price), 0);

    if (revenue === 0) {
      // Fallback: production × selling price
      const plans = await prisma.productionPlanItem.findMany({
        where: { plan: { planDate: { gte: startDate, lte: endDate }, restaurantId } },
        include: { recipe: { select: { sellingPrice: true } } },
      });
      revenue = plans.reduce(
        (s, p) => s + (p.recipe?.sellingPrice ? p.quantity * p.recipe.sellingPrice : 0),
        0
      );
    }

    const cmvPercent = revenue > 0 ? (totalCMV / revenue) * 100 : 0;

    let alertLevel: 'NORMAL' | 'WARNING' | 'CRITICAL' = 'NORMAL';
    let alertMessage: string | null = null;
    if (cmvPercent > 40) {
      alertLevel = 'CRITICAL';
      alertMessage = `CMV em ${cmvPercent.toFixed(1)}% — muito acima do ideal (28-35%). Ação urgente: revisar fichas técnicas, auditar perdas e renegociar com fornecedores.`;
    } else if (cmvPercent > 35) {
      alertLevel = 'WARNING';
      alertMessage = `CMV em ${cmvPercent.toFixed(1)}% — acima do range ideal. Monitorar perdas e revisar margens.`;
    } else if (cmvPercent < 20 && revenue > 0) {
      alertLevel = 'WARNING';
      alertMessage = `CMV em ${cmvPercent.toFixed(1)}% — muito baixo. Verificar se produção/vendas estão sendo registradas corretamente.`;
    }

    const snapshot = await (prisma as any).cMVSnapshot.create({
      data: {
        restaurantId,
        periodStart: startDate,
        periodEnd: endDate,
        periodDays: period,
        purchases,
        consumption,
        losses,
        totalCMV,
        revenue,
        cmvPercent,
        alertLevel,
        alertMessage,
        autoGenerated: isInternal,
      },
    });

    return NextResponse.json({ success: true, snapshot });
  } catch (error: any) {
    console.error('CMV snapshot error:', error);
    return NextResponse.json({ error: 'Erro ao criar snapshot CMV', details: error.message }, { status: 500 });
  }
}
